on: [push, pull_request]

name: CI

jobs:
  CI:
    name: Vérifications
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://build:build@localhost:5432/build
      DIRECT_URL: postgresql://build:build@localhost:5432/build
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
          cache: npm

      - name: Installer les dépendances
        run: npm ci

      - name: Vérifier TypeScript
        run: npm run typecheck

      - name: Run tests
        run: npm test

      - name: Vérifier ESLint
        run: npm run lint

      - name: Vérifier Prisma
        run: npx prisma generate && npx prisma validate

      - name: Construire l'application
        run: npm run build
